@tool
extends RefCounted

const FORMATS = ["obj", "stl", "ply", "glb", "gltf"]

# Export triangles at the current pose. No live scene nodes are modified.
static func export_meshes(path: String, sources: Array, options: Dictionary = {}) -> Error:
	var format := path.get_extension().to_lower()
	if not format in FORMATS: return ERR_FILE_UNRECOGNIZED
	if sources.is_empty(): return ERR_INVALID_PARAMETER
	var scale: float = options.get("scale", 1.0)
	if not is_finite(scale) or scale <= 0: return ERR_INVALID_PARAMETER
	var conversion := Basis.IDENTITY
	if options.get("z_up", false): conversion = Basis(Vector3.RIGHT, PI / 2)
	conversion = conversion.scaled(Vector3.ONE * scale)
	var meshes: Array[ArrayMesh] = []
	var names: Array[String] = []
	for source in sources:
		if not source is MeshInstance3D or source.mesh == null: continue
		var transform := Transform3D(conversion, Vector3.ZERO)
		if options.get("apply_transform", true): transform *= source.global_transform
		if absf(transform.basis.determinant()) < 0.000001: return ERR_INVALID_PARAMETER
		var mesh := ArrayMesh.new()
		for surface in source.mesh.get_surface_count():
			if source.mesh.surface_get_primitive_type(surface) != Mesh.PRIMITIVE_TRIANGLES: continue
			var arrays: Array = source.mesh.surface_get_arrays(surface).duplicate(true)
			var vertices: PackedVector3Array = arrays[Mesh.ARRAY_VERTEX]
			for i in vertices.size(): vertices[i] = transform * vertices[i]
			arrays[Mesh.ARRAY_VERTEX] = vertices
			# Flatten indices, reverse reflected winding, and retain UVs/normals.
			var indices: PackedInt32Array = arrays[Mesh.ARRAY_INDEX] if arrays[Mesh.ARRAY_INDEX] != null else PackedInt32Array()
			if indices.is_empty():
				for i in vertices.size(): indices.append(i)
			if indices.size() % 3 != 0: return ERR_INVALID_DATA
			if transform.basis.determinant() < 0:
				for i in range(0, indices.size(), 3):
					var swap := indices[i + 1]
					indices[i + 1] = indices[i + 2]
					indices[i + 2] = swap
			arrays[Mesh.ARRAY_INDEX] = indices
			if arrays[Mesh.ARRAY_NORMAL] != null:
				var normals: PackedVector3Array = arrays[Mesh.ARRAY_NORMAL]
				var normal_basis := transform.basis.inverse().transposed()
				for i in normals.size(): normals[i] = (normal_basis * normals[i]).normalized()
				arrays[Mesh.ARRAY_NORMAL] = normals
			# Tangents are regenerated by receiving applications when required.
			arrays[Mesh.ARRAY_TANGENT] = null
			mesh.add_surface_from_arrays(Mesh.PRIMITIVE_TRIANGLES, arrays)
			mesh.surface_set_material(mesh.get_surface_count() - 1, source.mesh.surface_get_material(surface))
		if mesh.get_surface_count() > 0:
			meshes.append(mesh)
			names.append(str(source.name).replace("\n", "_").replace("\r", "_").replace(" ", "_"))
	if meshes.is_empty(): return ERR_INVALID_PARAMETER
	if format in ["glb", "gltf"]: return _gltf(path, meshes, names)
	var file := FileAccess.open(path, FileAccess.WRITE)
	if file == null: return FileAccess.get_open_error()
	match format:
		"obj": _obj(file, meshes, names, options)
		"stl": _stl(file, meshes, options.get("binary", true))
		"ply": _ply(file, meshes)
	file.flush()
	var result := file.get_error()
	file.close()
	return result

static func _gltf(path: String, meshes: Array[ArrayMesh], names: Array[String]) -> Error:
	var root := Node3D.new()
	root.name = "Codis3D"
	for i in meshes.size():
		var node := MeshInstance3D.new()
		node.name = names[i]
		node.mesh = meshes[i]
		root.add_child(node)
	var document := GLTFDocument.new()
	document.root_node_mode = GLTFDocument.ROOT_NODE_MODE_MULTI_ROOT
	var state := GLTFState.new()
	var result := document.append_from_scene(root, state)
	if result == OK: result = document.write_to_filesystem(state, path)
	root.free()
	return result

static func _obj(file: FileAccess, meshes: Array[ArrayMesh], names: Array[String], options: Dictionary) -> void:
	file.store_line("# Codis3D OBJ export")
	var v_offset := 1
	var uv_offset := 1
	var n_offset := 1
	for object in meshes.size():
		file.store_line("o " + names[object])
		var mesh := meshes[object]
		for surface in mesh.get_surface_count():
			var arrays := mesh.surface_get_arrays(surface)
			var vertices: PackedVector3Array = arrays[Mesh.ARRAY_VERTEX]
			var indices: PackedInt32Array = arrays[Mesh.ARRAY_INDEX]
			var uv: PackedVector2Array = arrays[Mesh.ARRAY_TEX_UV] if arrays[Mesh.ARRAY_TEX_UV] != null else PackedVector2Array()
			var normals: PackedVector3Array = arrays[Mesh.ARRAY_NORMAL] if arrays[Mesh.ARRAY_NORMAL] != null else PackedVector3Array()
			var use_uv: bool = options.get("uvs", true) and uv.size() == vertices.size()
			var use_normals: bool = options.get("normals", true) and normals.size() == vertices.size()
			for v in vertices: file.store_line("v %s %s %s" % [v.x, v.y, v.z])
			if use_uv:
				for v in uv: file.store_line("vt %s %s" % [v.x, 1.0 - v.y])
			if use_normals:
				for n in normals: file.store_line("vn %s %s %s" % [n.x, n.y, n.z])
			for i in range(0, indices.size(), 3):
				var face := PackedStringArray()
				# Godot triangle fronts are clockwise; exchange formats are CCW.
				for j in [0, 2, 1]:
					var index := indices[i + j]
					var token := str(index + v_offset)
					if use_uv or use_normals:
						token += "/" + (str(index + uv_offset) if use_uv else "")
						if use_normals: token += "/" + str(index + n_offset)
					face.append(token)
				file.store_line("f " + " ".join(face))
			v_offset += vertices.size()
			if use_uv: uv_offset += uv.size()
			if use_normals: n_offset += normals.size()

static func _faces(meshes: Array[ArrayMesh]) -> PackedVector3Array:
	var result := PackedVector3Array()
	for mesh in meshes:
		var faces := mesh.get_faces()
		for i in range(0, faces.size(), 3):
			result.append_array(PackedVector3Array([faces[i], faces[i + 2], faces[i + 1]]))
	return result

static func _stl(file: FileAccess, meshes: Array[ArrayMesh], binary: bool) -> void:
	var faces := _faces(meshes)
	if binary:
		var header := PackedByteArray()
		header.resize(80)
		file.store_buffer(header)
		file.store_32(faces.size() / 3)
	else: file.store_line("solid Codis3D")
	for i in range(0, faces.size(), 3):
		var a := faces[i]
		var b := faces[i + 1]
		var c := faces[i + 2]
		var normal := (b - a).cross(c - a).normalized()
		if binary:
			for v in [normal, a, b, c]:
				file.store_float(v.x)
				file.store_float(v.y)
				file.store_float(v.z)
			file.store_16(0)
		else:
			file.store_line("facet normal %s %s %s\n outer loop" % [normal.x, normal.y, normal.z])
			for v in [a, b, c]: file.store_line("  vertex %s %s %s" % [v.x, v.y, v.z])
			file.store_line(" endloop\nendfacet")
	if not binary: file.store_line("endsolid Codis3D")

static func _ply(file: FileAccess, meshes: Array[ArrayMesh]) -> void:
	var faces := _faces(meshes)
	file.store_line("ply\nformat ascii 1.0\ncomment Codis3D export")
	file.store_line("element vertex %d\nproperty float x\nproperty float y\nproperty float z" % faces.size())
	file.store_line("element face %d\nproperty list uchar int vertex_indices\nend_header" % (faces.size() / 3))
	for v in faces: file.store_line("%s %s %s" % [v.x, v.y, v.z])
	for i in range(0, faces.size(), 3): file.store_line("3 %d %d %d" % [i, i + 1, i + 2])
